openapi: 3.0.3

info:
  title: go-sample-app
  version: 0.0.0

paths:
  /api/v1/greeting:
    get:
      summary: 挨拶
      description: 挨拶メッセージを取得する
      responses:
        "200":
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: string
                example: Hello, world!
  /api/v1/users:
    get:
      summary: ユーザー一覧の取得
      description: ユーザー一覧を取得する
      responses:
        "200":
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
  /api/v1/users/{userId}:
    get:
      summary: 特定のユーザーの取得
      description: 特定のユーザーを取得する
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"

components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int32
          description: ユーザーID
        name:
          type: string
          description: ユーザー名
      example:
        id: 1
        name: 田中太郎


servers:
  - url: http://localhost:8888
    description: ローカル環境
