openapi: 3.0.0
info:
  title: go-sample-app
  version: 0.0.0
tags: []
paths:
  /api/v1/greeting:
    get:
      operationId: Greeting_greeting
      summary: 挨拶
      description: 挨拶メッセージを取得する
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: string
  /api/v1/users:
    get:
      operationId: Users_getUsers
      summary: ユーザー一覧の取得
      description: ユーザー一覧を取得する
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Models.User'
  /api/v1/users/{userId}:
    get:
      operationId: Users_getUser
      summary: 特定のユーザーの取得
      description: 特定のユーザーを取得する
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Models.User'
components:
  schemas:
    Models.User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int32
          description: ユーザーID
        name:
          type: string
          description: ユーザー名
      example:
        id: 1
        name: 田中太郎
servers:
  - url: http://localhost:8888
    description: ローカル環境
    variables: {}
