// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock/client.go
//

// Package mock_sqs is a generated GoMock package.
package mock_sqs

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// SendBatchMessages mocks base method.
func (m *MockClient) SendBatchMessages(ctx context.Context, queueUrl string, messages []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendBatchMessages", ctx, queueUrl, messages)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendBatchMessages indicates an expected call of SendBatchMessages.
func (mr *MockClientMockRecorder) SendBatchMessages(ctx, queueUrl, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBatchMessages", reflect.TypeOf((*MockClient)(nil).SendBatchMessages), ctx, queueUrl, messages)
}

// SendMessage mocks base method.
func (m *MockClient) SendMessage(ctx context.Context, queueUrl, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, queueUrl, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockClientMockRecorder) SendMessage(ctx, queueUrl, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockClient)(nil).SendMessage), ctx, queueUrl, message)
}
